# D:\Texton\Texton.ai\services\docker-compose.postgres.yml
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: texton
      POSTGRES_PASSWORD: leaf123 # <-- CHANGE THIS
      POSTGRES_DB: texton_db
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
    networks:
      - texton-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U texton_user -d texton_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  texton-net:
    external: true