server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:texton_db
    driver-class-name: org.h2.Driver
    username: SA
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

application:
  security:
    jwt:
      secret-key: "Yjp8r2y9MJPXENMR+RukrUqEnpCCpPGJHpYdavLzThUHO03MzNQ7WqkkPw1e+PHmZjIrbOEzwg7SzWwhPUYfcg=="
      expiration: 86400000 # 24h

gemini:
  api-key: "AIzaSyApJfBcvN9gtBFqU_vPpnlQ_qYN5fdAri8"        # âœ… required by @Value("${gemini.api.key}")
  llm-model: "gemini-2.0-flash"
  embedding-model: "text-embedding-004"

s3:
  base-path: "D:/Texton/Texton.ai/s3/"

logging:
  level:
    root: INFO
    org.springframework.scheduling: DEBUG
    org.springframework.aop: DEBUG
    com.texton.backend: DEBUG
